### ISSUE TITLE
Conditionals in email template

### ISSUE THREAD

**Issue by donorservices** [visualbuilder/email-templates#22]
This looks like a great package but I don't see any documentation where it supports conditionals.  With email templates via blade we have @if() and @else to show/hide elements based on certain values, any chance a way to add conditionals could be added so we can do this in the email template via the included code editor?

Thanks.

**Comment by cannycookie** [comment]
Hey, yes i've often had situations where @if @else was needed but in the end i was able to find a way to use model attributes to define content, then you can put the business logic in the backend rather than in the view.  

in any model you can use 
```php
public function getSomeContentAttribute(){
..do your conditional stuff here
return $string??"";
}
``` 

Then in the email template use ##model.some_content## if its not applicable it will be replaced with an empty string;

Hope that helps
